In [1]:
#library(kableExtra)
#library(fs)
R.home()
# Si no dan error, ¡estamos listos para las tablas del libro!

[1] "/usr/lib/R"

In [2]:
# Forzamos a R a que ignore las carpetas locales por un segundo y use la del sistema
.libPaths("/usr/lib/R/library")
library(kableExtra)
#library(fs)

ERROR: Error: package or namespace load failed for ‘kableExtra’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘systemfonts’ 1.1.0 is being loaded, but >= 1.3.0 is required

In [3]:
install.packages("kableExtra", repos = "https://cran.rstudio.com/")
#install.packages("fs", repos = "https://cran.rstudio.com/")

Installing package into ‘/usr/lib/R/library’
(as ‘lib’ is unspecified)

Warning message in install.packages("kableExtra", repos = "https://cran.rstudio.com/"):
“'lib = "/usr/lib/R/library"' is not writable”

ERROR: Error in install.packages("kableExtra", repos = "https://cran.rstudio.com/"): unable to install packages

In [4]:
#library(kableExtra)
#library(agricolae)
#library(knitr)
#library(faraway)
library(XML)
library(ggplot2)
library(tidyverse)
library(readxl)
# funciones 
pregnum=function(resp,error=0.0001,peso=1,digresp=4,diger=digresp){
paste('{',peso,':NM:=',formatC(resp,digits=digresp,format = "f"),':',formatC(error,digits=diger,format = "f"),'}',sep='')
}
premch=function(resp=1,opciones,peso=1){
if(resp<1 | resp>length(opciones) ){stop("La respuesta debe ser un numero entre 1 y el numero de opciones")}  
for(i in 1:length(opciones)){
   if(i!=resp){opciones[i]=paste('~%0%',opciones[i],'',sep="")
}else{opciones[i]=paste('~=',opciones[i],'',sep="")} 
    }
gsub(" ", "",paste0( c(paste('{',peso,':MULTICHOICE:'), noquote(opciones),'}' ),collapse=""))
} 
# doc para guardar en formato xml 
NombreCat="Limpieza/parse_num"
doc=newXMLDoc()
root=newXMLNode("quiz",doc=doc)
question=newXMLNode("question",attrs = list(type="category"),parent = root)
category=newXMLNode("category",parent = question)
text=newXMLNode("text",NombreCat,parent = category)
info=newXMLNode("info",attrs = list(format="html"),parent = question)  
textInf=newXMLNode("text","texto",parent = info)
idnum=newXMLNode("idnumber",parent=question)
# funcion para agregar la pregunta al xml 
addquestion=function(NomPr,textopregunta){
questionpr=newXMLNode("question",attrs = list(type="cloze"),parent = root)
nombrepr=newXMLNode("name",parent = questionpr)
textNomPre=newXMLNode("text",NomPr,parent =nombrepr)
questiontext=newXMLNode("questiontext",attrs = list(format="html"),parent = questionpr)
textqt=newXMLNode("text",textopregunta,parent =questiontext)
generalfeedback=newXMLNode("generalfeedback",attrs = list(format="html"),parent = questionpr)
textgf=newXMLNode("text",parent = generalfeedback)
penalty=newXMLNode("penalty",0.3333333,parent=questionpr)
hidden=newXMLNode("hidden",0,parent=questionpr)
idnumber=newXMLNode("idnumber",parent=questionpr)
}

ERROR: Error in library(XML): there is no package called ‘XML’

In [1]:
setwd("~/Documents/Cursos/Laboratorio")
# lectura de los datos 
library(readxl)
df=read_excel("~/Documents/Cursos/Laboratorio/DatosEstudiantes.xlsx")
head(df)

ERROR: Error in setwd("~/Documents/Cursos/Laboratorio"): no es posible cambiar el directorio de trabajo

In [27]:
glimpse(df)

Rows: 45
Columns: 9
$ Edad         <dbl> 16, 18, 16, 16, 17, 17, 16, NA, 17, 17, 18, 18, 18, 18, 1…
$ Sexo         <chr> "Mujer", "Mujer", "Mujer", "Mujer", "Hombre", "Hombre", "…
$ Tcolegio     <chr> "Público", "Público", "Público", "Público", "Privado", "P…
$ Estrato      <dbl> 1, 1, 2, 2, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 1, 3, …
$ Peso         <chr> "47", "47", "59", "59", "68", "51", "79", "46", "58", "56…
$ Estatura     <chr> "1.6", "158", "1.71", "1.71", "175", "1.65", "1.67", "1.5…
$ Afisica      <chr> "Ningún día a la semana", "Cinco días a la semana", "Ning…
$ satisfaccion <dbl> 5, 7, 8, 8, 9, 8, 9, 8, 5, 9, 9, 6, 9, 8, 8, 7, 8, 7, 9, …
$ Nhermanos    <dbl> 2, 3, 2, 2, 4, 3, 3, 2, 3, 1, 7, 7, 5, 3, 3, 3, 4, 1, 2, …

In [28]:
# Convertir peso a numérica 
df_limpio=df|>mutate(Peso=parse_number(Peso)) 
#Convertir estatura a numérica
df_limpio=df_limpio|>mutate(Estatura=parse_number(Estatura))
# Estaturas en centímetro, pasarlas a metro (dividir por 100)  
df_limpio <- df_limpio |>
  mutate(Estatura= if_else(
    Estatura > 2.0,
    Estatura / 100,
    Estatura  
  ))
summary(df_limpio$Estatura) 
# Datos faltantes en peso 
Nas=df_limpio|>summarise(NoNa=sum(is.na(Peso))) 
resp0=Nas$NoNa
df_r=df_limpio|>summarise(N=n(),Min=min(Peso,na.rm=TRUE),Q1=quantile(Peso,probs=c(0.25),na.rm=TRUE),Mediana=median(Peso,na.rm=TRUE),Media=mean(Peso,na.rm=TRUE))
df_r

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  1.500   1.580   1.650   1.646   1.710   1.780

    N  Min Q1    Mediana Media
25% 45 39  49.75 57      56.92045

In [29]:
# pregunta peso

In [30]:
glimpse(df_limpio)

Rows: 45
Columns: 9
$ Edad         <dbl> 16, 18, 16, 16, 17, 17, 16, NA, 17, 17, 18, 18, 18, 18, 1…
$ Sexo         <chr> "Mujer", "Mujer", "Mujer", "Mujer", "Hombre", "Hombre", "…
$ Tcolegio     <chr> "Público", "Público", "Público", "Público", "Privado", "P…
$ Estrato      <dbl> 1, 1, 2, 2, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 1, 3, …
$ Peso         <dbl> 47, 47, 59, 59, 68, 51, 79, 46, 58, 56, 65, 54, 53, 53, 5…
$ Estatura     <dbl> 1.60, 1.58, 1.71, 1.71, 1.75, 1.65, 1.67, 1.54, 1.55, 1.6…
$ Afisica      <chr> "Ningún día a la semana", "Cinco días a la semana", "Ning…
$ satisfaccion <dbl> 5, 7, 8, 8, 9, 8, 9, 8, 5, 9, 9, 6, 9, 8, 8, 7, 8, 7, 9, …
$ Nhermanos    <dbl> 2, 3, 2, 2, 4, 3, 3, 2, 3, 1, 7, 7, 5, 3, 3, 3, 4, 1, 2, …

Completar estadísticas básicas de peso y estatura

In [33]:
# Peso 
columna='Peso'
tab1='<table style="border-collapse:collapse;border-color:#aaa;border-spacing:0" class="tg"><thead>
<tr><th style="background-color:#f38630;border-color:inherit;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">N</th><th style="background-color:#f38630;border-color:inherit;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">Min</th><th style="background-color:#f38630;border-color:inherit;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">Q1</th>
<th style="background-color:#f38630;border-color:inherit;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">Mediana</th><th style="background-color:#f38630;border-color:inherit;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">Media</th></tr>
</thead>
<tbody>
<tr><td style="background-color:#fff;border-color:inherit;border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">resp1</td><td style="background-color:#fff;border-color:inherit;border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">resp2</td><td style="background-color:#fff;border-color:inherit;border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">resp3</td><td style="background-color:#fff;border-color:inherit;border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">resp4</td>
<td style="background-color:#fff;border-color:inherit;border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">resp5</td></tr>
</tbody></table>' 

rsp1=pregnum(df_r$N,error=0,digresp=0)
rsp1
rsp2=pregnum(df_r$Min,error=0,digresp=0)
rsp2
rsp3=pregnum(df_r$Q1,error=0.01,digresp=2)
rsp3
rsp4=pregnum(df_r$Mediana,error=0.01,digresp=2)
rsp4
rsp5=pregnum(df_r$Media,error=0.005,digresp=3)
rsp5
tab1=gsub(pattern = "resp1", replacement = rsp1, x = tab1)
tab1=gsub(pattern = "resp2", replacement = rsp2, x = tab1)
tab1=gsub(pattern = "resp3", replacement = rsp3, x = tab1)
tab1=gsub(pattern = "resp4", replacement = rsp4, x = tab1)
tab1=gsub(pattern = "resp5", replacement = rsp5, x = tab1) 
opc0=c('is_na(Peso)','mutate','n()','mean(Peso)','parse_number','Peso','summarise','min')
opc1=c('min','mean','median','quantile','max','var','sd','Media','Median')  

text1p=paste("El archivo <code>DatosEstudiantes.xlsx</code> contiene datos tomados de estudiantes de primer semestre durante un experimento que buscaba evaluar el nivel de satisfacción de los estudiantes con el servicio prestado por la Universidad. Haga la lectura de los datos y responda:")
text2p=paste("Cuántos datos faltantes hay en la columna <code>",columna,"</code>:",pregnum(resp0,digresp=1,error=00),sep=" ")
text3p=paste("Un posible codigo, en lenguaje <code>R</code>, usando la librería <code>tidyverse</code> y el <code>pipe</code> para obtener la respuesta a la pregunta anterior es: <br> <pre> 
library(tidyverse) <br>
library(readxl) <br>
df=read_excel('DatosEstudiantes.xlsx') <br> 
df=",premch(2,opc0),"(",columna,"=",premch(5,opc0),"(",premch(6,opc0),")|>",premch(7,opc0),"(sum(is.na(",columna,")))</pre>") 
text4p=paste( "<br> Complete la siguiente tabla con estadísticas descriptivas básicas de la columna <code>",columna,"</code> <br> " )
text5p=paste("Un posible codigo, en lenguaje <code>R</code>, usando la librería <code>tidyverse</code> y el <code>pipe</code> para obtener la respuesta a la pregunta anterior es: <br> <pre> 
library(tidyverse) <br>
library(readxl) <br> 
df=read_excel('DatosEstudiantes.xlsx') <br>
df|>",premch(7,opc0),"(N=n(),Min=",premch(1,opc1),"(",columna,",na.rm=TRUE),Q1=",premch(4,opc1),"(",columna,",na.rm=TRUE),",premch(9,opc1),"=",premch(3,opc1),"(",columna,",na.rm=TRUE)",premch(8,opc1),"=",premch(2,opc1),"(",columna,",na.rm=TRUE)  </pre>")

texto_preg=paste(text1p,text2p,text3p,text4p,tab1,text5p,sep='<br>')

#summarise(N=n(),Min=min(Peso,na.rm=TRUE),Q1=quantile(Peso,probs=c(0.25),na.rm=TRUE),Mediana=median(Peso,na.rm=TRUE),Media=mean(Peso,na.rm=TRUE))

NomPreg="Filter"
semilla=1
Nombre_pre=paste(NomPreg,semilla,sep=" ") 
Nombre_pre
#texto_preg

[1] "{1:NM:=45:0}"

[1] "{1:NM:=39:0}"

[1] "{1:NM:=49.75:0.01}"

[1] "{1:NM:=57.00:0.01}"

[1] "{1:NM:=56.920:0.005}"

[1] "Filter 1"

In [ ]:
# agrega pregunta 
addquestion(NomPr=Nombre_pre,textopregunta =texto_preg)

In [34]:
# Convertir peso a numérica 
#df_limpio=df|>mutate(Nhermanos=parse_number(Peso)) 
#Convertir estatura a numérica
#df_limpio=df_limpio|>mutate(Estatura=parse_number(Estatura))
# Estaturas en centímetro, pasarlas a metro (dividir por 100)  
#df_limpio <- df_limpio |>
#  mutate(Estatura= if_else(
#    Estatura > 2.0,
#    Estatura / 100,
#    Estatura  
#  ))
#summary(df_limpio$Estatura) 
# Datos faltantes en peso 

# No hermanos 
columna='Nhermanos'


Nas=df|>summarise(NoNa=sum(is.na(Nhermanos))) 
resp0=Nas$NoNa
df_r=df|>summarise(N=n(),Min=min(Nhermanos,na.rm=TRUE),Q1=quantile(Nhermanos,probs=c(0.25),na.rm=TRUE),Mediana=median(Nhermanos,na.rm=TRUE),Media=mean(Nhermanos,na.rm=TRUE))
df_r

    N  Min Q1 Mediana Media
25% 45 1   2  3       2.866667

In [36]:

tab1='<table style="border-collapse:collapse;border-color:#aaa;border-spacing:0" class="tg"><thead>
<tr><th style="background-color:#f38630;border-color:inherit;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">N</th><th style="background-color:#f38630;border-color:inherit;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">Min</th><th style="background-color:#f38630;border-color:inherit;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">Q1</th>
<th style="background-color:#f38630;border-color:inherit;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">Mediana</th><th style="background-color:#f38630;border-color:inherit;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">Media</th></tr>
</thead>
<tbody>
<tr><td style="background-color:#fff;border-color:inherit;border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">resp1</td><td style="background-color:#fff;border-color:inherit;border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">resp2</td><td style="background-color:#fff;border-color:inherit;border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">resp3</td><td style="background-color:#fff;border-color:inherit;border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">resp4</td>
<td style="background-color:#fff;border-color:inherit;border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:top;word-break:normal">resp5</td></tr>
</tbody></table>' 

rsp1=pregnum(df_r$N,error=0,digresp=0)
rsp1
rsp2=pregnum(df_r$Min,error=0,digresp=0)
rsp2
rsp3=pregnum(df_r$Q1,error=0.01,digresp=2)
rsp3
rsp4=pregnum(df_r$Mediana,error=0.01,digresp=2)
rsp4
rsp5=pregnum(df_r$Media,error=0.005,digresp=3)
rsp5
tab1=gsub(pattern = "resp1", replacement = rsp1, x = tab1)
tab1=gsub(pattern = "resp2", replacement = rsp2, x = tab1)
tab1=gsub(pattern = "resp3", replacement = rsp3, x = tab1)
tab1=gsub(pattern = "resp4", replacement = rsp4, x = tab1)
tab1=gsub(pattern = "resp5", replacement = rsp5, x = tab1) 

text1p=paste("El archivo <code>DatosEstudiantes.xlsx</code> contiene datos tomados de estudiantes de primer semestre durante un experimento que buscaba evaluar el nivel de satisfacción de los estudiantes con el servicio prestado por la Universidad. Haga la lectura de los datos y responda:")
text2p=paste("Cuántos datos faltantes hay en la columna <code>",columna,"</code>:",pregnum(resp0,digresp=1,error=00),sep=" ")
text3p=paste("Un posible codigo, en lenguaje <code>R</code>, usando la librería <code>tidyverse</code> y el <code>pipe</code> para obtener la respuesta a la pregunta anterior es: <br> <pre> 
library(tidyverse) <br>
library(readxl) <br>
df=read_excel('DatosEstudiantes.xlsx') <br> 
df=",premch(2,opc0),"(",columna,"=",premch(5,opc0),"(",premch(6,opc0),")|>",premch(7,opc0),"(sum(is.na(",columna,")))</pre>") 
text4p=paste( "<br> Complete la siguiente tabla con estadísticas descriptivas básicas de la columna <code>",columna,"</code> <br> " )
text5p=paste("Un posible codigo, en lenguaje <code>R</code>, usando la librería <code>tidyverse</code> y el <code>pipe</code> para obtener la respuesta a la pregunta anterior es: <br> <pre> 
library(tidyverse) <br>
library(readxl) <br> 
df=read_excel('DatosEstudiantes.xlsx') <br>
df|>",premch(7,opc0),"(N=n(),Min=",premch(1,opc1),"(",columna,",na.rm=TRUE),Q1=",premch(4,opc1),"(",columna,",na.rm=TRUE),",premch(9,opc1),"=",premch(3,opc1),"(",columna,",na.rm=TRUE)",premch(8,opc1),"=",premch(2,opc1),"(",columna,",na.rm=TRUE)  </pre>")

texto_preg=paste(text1p,text2p,text3p,text4p,tab1,text5p,sep='<br>')
NomPreg="Filter"
semilla=2
Nombre_pre=paste(NomPreg,semilla,sep=" ")

[1] "{1:NM:=45:0}"

[1] "{1:NM:=1:0}"

[1] "{1:NM:=2.00:0.01}"

[1] "{1:NM:=3.00:0.01}"

[1] "{1:NM:=2.867:0.005}"

In [31]:
# agrega pregunta 
addquestion(NomPr=Nombre_pre,textopregunta =texto_preg)

In [107]:
saveXML(doc, file="PreguntasParse.xml")